### PR TITLE
update

### PR DESCRIPTION
**Pull request by red-rj**
- StandardOutput of get project info and audio mixdown now use UTF8 encoding
- LogService can now be used as a singleton
- New log intances throughout the program
- Made a new Browse blend button that shows only on Linux to avoid that "needing to hold down the mouse button to browse recent blends" bug
- Rearranged all Linux specific code

### CODE REVIEW

**Comment by jendabek** [comment]
Sorry for the delay in my BRC activity, I have very little time for it now.
I added you as a collaborator so you should be able to make changes directly in my fork (if you want to).
I tried to build the latest merge request and it has an issue with some of your code


Any ideas?

**Comment by RedRaptor93** [comment]
Thank you, I was about to ask about having write access to the repo. Due to some issues in college I have less subjects then expected, and so more free time

I look into that issue when I get home.

Em 3 de mai de 2017, em 07:57, "Jan Kadeřábek" <notifications@github.com> escreveu:

Sorry for the delay in my BRC activity, I have very little time for it now.
I added you as a collaborator so you should be able to make changes directly in my fork (if you want to).
I tried to build the latest merge request and it has an issue with some of your code

Any ideas?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Em 3 de mai de 2017 07:57, em 07:57, "Jan Kadeřábek" <notifications@github.com> escreveu:

**Comment by RedRaptor93** [comment]
Ok that must be a problem with your Visual Studio, here its all fine, no errors.

image

**Comment by jendabek** [comment]
What .NET Framework version do you use?

**Comment by RedRaptor93** [comment]
the latest .NET installed on my machine is 4.6.1 but I don't think that matters since the target .NET of the project is the same.

I'm also using Visual Studio 2017.

**Comment by jendabek** [comment]
I will look at it tomorrow. 
Can you please attach that .bat file for Windows 7 into some next release zip?

**Comment by RedRaptor93** [comment]
I just drafted a new release, but did not include the bat... but I added a utilities folder with that bat included, also pointed to it in the readme

**Pull request merged**
